### ISSUE TITLE
На моем сервере нет ядра

### ISSUE THREAD

**Issue by erxson** [TerComPy/ModernWhitelist#1]
я тип тоже прогер но такую ошибку впервые вижу
Exit code: 1
<img width="960" alt="{FA36B270-04B0-474C-9064-52CE19CF542A}" src="https://github.com/user-attachments/assets/dce95888-3218-44b4-bbc9-4d51ab128af2">

**Comment by ProstoyArtemka** [comment]
+, у меня такая же ошибка, игроки жалуются

**Comment by TerComPy** [comment]
Error: Unable to access jarfile server.jar
Ошибка вообще не из-за моего плагина :)
